name: CD to GCS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout soruce code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Lint and test
        if: github.event_name != 'workflow_dispatch'
        run: npm run lint

      - name: Build with Vite
        run: npm run build

      - name: Setup google service account
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Upload dist to GCS
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: 'dist/**'
          destination: '${{ secrets.BUCKET_NAME }}'
